services:
  tic-tac-toe:
    image: tic-tac-toe:build-5
    container_name: tictactoe
    restart: always
    env_file:
      - .env
    entrypoint:
      - /bin/sh
      - -c
      - | 
        flask run --host=0.0.0.0
    ports:
      - 5055:5000
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    container_name: ferretdb
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb

networks:
  default:
    name: tictactoe